# Copyright 2025 Juspay
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.txt

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field
from juspay_dashboard_mcp.api_schema.headers import WithHeaders


class ListPayoutOrdersPayload(WithHeaders):
    dateFrom: str = Field(
        ...,
        description="Start date/time in ISO 8601 format (e.g., '2025-03-28T14:16:00Z'). Specifies the beginning of the time range for retrieving payout orders.",
    )
    dateTo: str = Field(
        ...,
        description="End date/time in ISO 8601 format (e.g., '2025-03-28T15:16:00Z'). Specifies the end of the time range for retrieving payout orders.",
    )
    limit: Optional[int] = Field(
        100,
        description="Number of payout orders to retrieve. Optional, defaults to 100. Maximum allowed value is 100.",
        ge=1,
        le=100
    )
    offset: Optional[int] = Field(
        0, 
        description="Pagination offset for retrieving payout orders. Optional, defaults to 0. Used to skip a specific number of records for pagination.",
        ge=0
    )


class GetPayoutOrderDetailsPayload(WithHeaders):
    order_id: str = Field(
        ..., 
        description="Unique payout order ID for which details are to be fetched. Can also be a fulfillment ID or transaction ID, which will be automatically processed to extract the base order ID if the initial request fails."
    )


class GetPayoutApprovalLinkPayload(WithHeaders):
    merchantOrderId: str = Field(
        ...,
        min_length=1,
        description="Merchant order ID for the payout awaiting maker-checker approval.",
    )


class PayoutPayeeDocument(BaseModel):
    docId: str = Field(..., description="Document identifier, for example PAN number.")
    docType: str = Field(..., description="Document type, for example PAN.")

    class Config:
        extra = "allow"


class PayoutPayeeAdditionalDetails(BaseModel):
    documents: List[PayoutPayeeDocument] = Field(
        ..., description="Payee documents required for supported payout gateways."
    )
    payeeType: str = Field(..., description="Payee type, for example PARTNER, PUBLTD, PVTLTD, PROP, SOC, TRUST, or GOVT.")
    businessModel: str = Field(..., description="Business model of the payee, for example Ecommerce.")

    class Config:
        extra = "allow"


class CreatePayoutOrderPayload(WithHeaders):
    orderId: str = Field(
        ...,
        min_length=4,
        max_length=64,
        pattern=r"^[A-Za-z0-9_\-@]+$",
        description="Unique payout order reference. Min length 4, max length 64. Supports alphanumeric values plus _, -, and @.",
    )
    beneType: Literal["CARD", "PLAIN_CARD", "UPI_ID", "ACCOUNT_IFSC", "WALLET", "BENE_ID", "PAYOUT_LINK"] = Field(
        ...,
        description="Beneficiary payment type.",
    )
    amount: float = Field(..., ge=1, description="Total payout order amount. Minimum amount is 1 and supports up to 2 decimal points.")
    customerId: str = Field(..., max_length=64, description="Unique customer ID generated by the merchant.")
    customerPhone: str = Field(..., description="Customer mobile number. A dummy value may be passed if unavailable.")
    customerEmail: str = Field(..., description="Customer email address. A dummy value may be passed if unavailable.")
    beneName: Optional[str] = Field(None, description="Beneficiary name.")
    beneCardReference: Optional[str] = Field(None, description="Beneficiary card reference.")
    beneBankCode: Optional[str] = Field(None, description="Beneficiary bank code.")
    beneCardType: Optional[str] = Field(None, description="Beneficiary card type.")
    beneBrand: Optional[str] = Field(None, description="Beneficiary card brand.")
    beneAccount: Optional[str] = Field(None, description="Beneficiary bank account number.")
    beneIfsc: Optional[str] = Field(None, description="Beneficiary IFSC code.")
    beneVpa: Optional[str] = Field(None, description="Beneficiary UPI VPA.")
    preferredMethodList: Optional[List[str]] = Field(None, description="Optional payout methods to prioritize.")
    beneWalletIdentifier: Optional[str] = Field(None, description="Beneficiary wallet identifier.")
    beneWalletBrand: Optional[str] = Field(None, description="Beneficiary wallet brand.")
    beneWalletIdentifierType: Optional[str] = Field(None, description="Beneficiary wallet identifier type.")
    beneId: Optional[str] = Field(None, description="Existing beneficiary ID.")
    orderType: Optional[Literal["APPROVE_AND_FULFILL_ONLY"]] = Field(
        None,
        description="Optional payout order type. Defaults to maker-checker mode when omitted.",
    )
    beneLegalEntityIdentifier: Optional[str] = Field(None, description="Beneficiary legal entity identifier.")
    last4ofCard: Optional[str] = Field(None, description="Last four digits of the beneficiary card.")
    udf1: Optional[str] = Field(None, description="Order-level user-defined field 1.")
    udf2: Optional[str] = Field(None, description="Order-level user-defined field 2.")
    udf3: Optional[str] = Field(None, description="Order-level user-defined field 3.")
    udf4: Optional[str] = Field(None, description="Order-level user-defined field 4.")
    udf5: Optional[str] = Field(None, description="Order-level user-defined field 5.")
    scheduleTime: Optional[str] = Field(None, description="Scheduled payout time.")
    fulfillmentCurrency: Optional[str] = Field(None, description="Fulfillment currency.")
    sourceCurrency: Optional[str] = Field(None, description="Source currency.")
    payeeAdditionalDetails: Optional[PayoutPayeeAdditionalDetails] = Field(None, description="Additional payee details required for supported gateways.")
    beneMobileNo: Optional[str] = Field(None, description="Beneficiary mobile number.")
    idempotencyKey: Optional[str] = Field(None, description="Idempotency key for payout order creation.")

    class Config:
        extra = "allow"
