name: Release Docker Images
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4
      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 🛠️ Build & Push `juspay-dashboard-mcp` (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-dashboard-mcp:latest
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-dashboard-mcp:${{ github.ref_name }}
      - name: 🛠️ Build & Push `juspay-mcp` (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-mcp:latest
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-mcp:${{ github.ref_name }}
      - name: 🛠️ Build & Push `juspay-dashboard-mcp for sse` (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dashboard-sse
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-dashboard-mcp:sse-latest
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-dashboard-mcp:sse-${{ github.ref_name }}
      - name: 🛠️ Build & Push `juspay-mcp for sse` (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.sse
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-mcp:sse-latest
            ${{ secrets.DOCKERHUB_NAMESPACE }}/juspay-mcp:sse-${{ github.ref_name }}
